### ISSUE TITLE
Error on Mac os

### ISSUE THREAD

**Issue by meistervid** [ethanfann/slackmojis-dl#31]
Hello and thank you for writing this library. When working with network requests apparently mac os creates a .DS_Store file, which triggers an error when scanning the emojis folder:
> Mac OS X has an annoying habit of littering network shares with .DS_Store (Desktop Services Store) files. If you only use Mac OS X and other Unix based systems you may never actually see them, but in mixed environments they can become a bit of a nuisance. There is nothing critical stored in .DS_Store files, just Finder specific settings, such as icons size and location, view settings, etc.

[Source](https://www.mysysadmintips.com/mac-os-x/582-stop-ds-store-file-creation-by-mac-os-x)

So mac users need to temporarily disable the creation of this file when downloading icons by running the following command in the console:
`defaults write com.apple.desktopservices DSDontWriteNetworkStores true`
and once they are done reverting that:
`defaults write com.apple.desktopservices DSDontWriteNetworkStores false`

Maybe you could include this in the readme file! :)

**Comment by ethanfann** [comment]
Hi! Thanks for bringing this up and I'll poke around to see if I can reproduce. In the meantime, do you happen to have a screenshot of the error thrown?

**Comment by ethanfann** [comment]
I've published an update that removes the detection of dotfiles/hidden files which should resolve the issue you're experiencing.
